# Codalab submission
extra_packages: []  # Paths
active_model_files: []  # With respect to model_dir
is_submission: False

# AutoCV, defaults from kakaobrain
autocv:
  model:
    architecture: ResNet18

  optimizer:
    lr: 0.025
    wd: 0.00025
    momentum: 0.9
    type: SGD
    amsgrad: False
    nesterov: True
    scheduler: plateau
    freeze_portion: 0.0
    warmup_multiplier: 2.0
    warm_up_epoch: 5

  dataset:
    train_info_sample: 256
    cv_valid_ratio: 0.1
    max_valid_count: 256
    max_size: 64
    base: 16  # input size should be multipliers of 16
    max_times: 8
    enough_count:
      image: 10000
      video: 1000
    batch_size: 32
    steps_per_epoch: 30
    max_epoch: 1000  # initial value
    batch_size_test: 256

  checkpoints:
    keep: 50

  conditions:
    score_type: auc
    early_epoch: 1
    skip_valid_score_threshold: 0.90  # if bigger then 1.0 is not use
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 90
    test_after_at_least_seconds_step: 2
    threshold_valid_score_diff: 0.001
    threshold_valid_best_score: 0.997
    max_inner_loop_ratio: 0.2
    min_lr: 0.000001  # = 1e-6, need explicit version to be parsed by yaml
    use_fast_auto_aug: True
    output_majority_first: False
    first_simple_model: False
    simple_model: RF